config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show'



  post 'tasks', to: 'tasks#create'

  get "tasks/:id/edit", to:"tasks#edit"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @tasks = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(params[:task])
    @task.save
    redirect_to task_path(@task)
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_with model: @tasks do |task| %>
  <%= f.label :title %>
  <%= f.label :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1> My Tasks </h1>
<ul>
<% @tasks.each do |task| %>
  <li><%= link_to task.title, tasks_path(task) %></li>
    <% end %>
<ul>
 <a href="tasks/:id"> Details </1>

app/views/tasks/new.html.erb
<%= form_with model: @task do |task| %>
  <%= task.label :title %>
  <%= task.text_field :details %>
  <%= task.submit %>
<% end %>

app/views/tasks/show.html.erb
<h2> details </h2>
<p> <%= task.title %><p>
<p> <%= task.details %></p>
<p> <%= task.completed %><p>